version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cattr-app
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/var/www/html

volumes:
  mysql-data:
